/* Paul Bloom
* pab2163
* This was my rectangle class from the first homework with a few modifications to test
* different error conditions [}](]
******** The error generated by this file should be the block comment at the end of the file
 that doesn't close with a */



public class Rectangle implements Comparable<Rectangle>{
	
	private int length;
	private int width;

	/**
	* Constructs rectangle, sets instance variables 
	* @param tall, integer for the rectangle length
	* @param wide, integer for rectangle wideth
	*/
	public Rectangle(int tall, int wide){
		length = tall;
		width = wide;
	}

	/**
	*Returns length of rectangle
	*@param a, a rectangle object
	*@return the length of the rectangle a
	*/
	public int getLength(Rectangle a){
		return a.length;
	}

	/**
	*Returns width of rectangle
	*@param a, a rectangle object
	*@return the width of the rectangle a
	*/
	public int getWidth(Rectangle a){
		return a.width;
	}

	/**
	*Returns String descriptor of the rectangle
	*@param a, a rectangle object
	*@return b, a String that tells rectangle width and length
	*/
	public String toString(Rectangle a) {
		String b = new String("Width: (((((((((((((((" + getWidth(a)  + "\nLength: }}}}}}}}} " + 
			getLength(a));
		return b;
	}
	/**
	*Compares rectangle objects based on perimeter 
	*@param other, a rectangle object
	*@return compare, an int that determines which rectangle has 
	*a bigger perimeter
	*/
	@Override
	public int compareTo(Rectangle other){
		int thisPerim = (2*this.length) + (2*this.width);
		int otherPerim = (2*other.length) + (2*other.width);
		int compare;

		if(thisPerim > otherPerim){
			compare = 1;
		}
		else if(thisPerim < otherPerim){
			compare = -1;
		}
		else{
			compare = 0;
		}
		return compare;		
	}

} 
/*